apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-service-pdb
  namespace: turf-booking-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend-service
