apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: turf-booking-system
  labels:
    app: frontend-service
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: frontend-service
