server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    location /health {
        access_log off;
        default_type application/json;
        return 200 '{"status":"UP","service":"frontend-service"}';
    }

    location /ready {
        access_log off;
        default_type application/json;
        return 200 '{"status":"READY","service":"frontend-service"}';
    }

    location /metrics {
        access_log off;
        default_type text/plain;
        return 200 'frontend_up 1\n';
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
