apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: ClusterSecretStore
  target:
    name: auth-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: turf-booking/dev/auth-service
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: user-service-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: ClusterSecretStore
  target:
    name: user-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: turf-booking/dev/user-service
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: turf-service-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: ClusterSecretStore
  target:
    name: turf-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: turf-booking/dev/turf-service
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: booking-service-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: ClusterSecretStore
  target:
    name: booking-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: turf-booking/dev/booking-service
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: media-service-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: ClusterSecretStore
  target:
    name: media-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: turf-booking/dev/media-service
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: notification-service-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: ClusterSecretStore
  target:
    name: notification-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: turf-booking/dev/notification-service
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-gateway-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: ClusterSecretStore
  target:
    name: api-gateway-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: turf-booking/dev/api-gateway
