apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: turf-booking-system

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- mongodb.yaml
- ingress.yaml
- auth-service/deployment.yaml
- auth-service/service.yaml
- auth-service/hpa.yaml
- auth-service/pdb.yaml
- turf-service/deployment.yaml
- turf-service/service.yaml
- turf-service/hpa.yaml
- turf-service/pdb.yaml
- booking-service/deployment.yaml
- booking-service/service.yaml
- booking-service/hpa.yaml
- booking-service/pdb.yaml
- api-gateway/deployment.yaml
- api-gateway/service.yaml
- api-gateway/hpa.yaml
- api-gateway/pdb.yaml
- frontend-service/deployment.yaml
- frontend-service/service.yaml
- frontend-service/hpa.yaml
- frontend-service/pdb.yaml
