apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: turf-booking-system
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turf-service
  namespace: turf-booking-system
spec:
  replicas: 2
